baseurl = "https://websitename.github.io/"
canonifyurls = false
copyright = "Open Source under the MIT license."
disableKinds = ["404", "taxonomyTerm", "taxonomy"]
enableEmoji = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
relativeurls = false
theme = "startbootstrap-clean-blog"
title = "Website Title"
[author]
name = ""
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
dateform = "Mon, Jan 2, 2006"
description = ""
email = "...@users.noreply.github.com"
image = "/uploads/2018/01/01/unsplash-garrett-parker-247225.jpg"
[[params.social]]
title = "facebook"
url = "https://www.facebook.com/FACEBOOKHANDLE"
[taxonomies]
category = "categories"
tag = "tags"
